-- Generated by Ora2Pg, the Oracle database Schema converter, version 4.1
-- Copyright 2000-2004 Gilles DAROLD. All rights reserved.
--
-- This program is free software; you can redistribute it and/or modify it under
-- the same terms as Perl itself.

BEGIN TRANSACTION;

CREATE SEQUENCE ad_error_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483646 START 1 CACHE 20;
CREATE SEQUENCE w_basket_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483646 START 1 CACHE 20;
CREATE SEQUENCE ad_pinstance_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483646 START 1 CACHE 20;
CREATE SEQUENCE t_spool_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483646 START 1 CACHE 20;

END TRANSACTION;
